import argparse
import asyncio
import json
import os
import subprocess
import sys
import tempfile
import warnings
from collections import Counter, defaultdict
from datetime import datetime

import numpy as np

os.environ["OBJC_DISABLE_INITIALIZE_FORK_SAFETY"] = "YES"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

warnings.filterwarnings("ignore", message=".*SymbolDatabase.GetPrototype.*")
warnings.filterwarnings("ignore", message=".*Mean of empty slice.*")
warnings.filterwarnings("ignore", message=".*invalid value encountered.*")

sys.path.append(os.path.dirname(os.path.abspath(__file__)))


LABELS = {
    0: "Authentic",
    1: "Suspicious",
    2: "AI",
}

FEATURE_NAMES = [
    'texture_mean', 'texture_max', 'texture_std',
    'bio_mean', 'bio_max', 'bio_std',
    'color_mean', 'color_max', 'color_std',
    'digital_penalty',
    'semantic',
    'vit_mean', 'vit_max', 'vit_std',
    'metadata_score',
    'metadata_hits'
]


def score_to_class(score, ai_threshold=0.58, suspicious_threshold=0.32):
    if score >= ai_threshold:
        return 2
    if score >= suspicious_threshold:
        return 1
    return 0


def read_urls(path):
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip() and not line.startswith("#")]


def load_sources(base_dir, limit_per_class=None):
    sources = [
        ("urls_real.txt", 0, "real"),
        ("urls_suspicious.txt", 1, "suspicious"),
        ("urls_fake.txt", 2, "ai"),
    ]
    examples = []
    for filename, label, bucket in sources:
        path = os.path.join(base_dir, "training_data", filename)
        if not os.path.exists(path):
            continue
        urls = read_urls(path)
        if limit_per_class:
            urls = urls[:limit_per_class]
        for url in urls:
            examples.append({
                "url": url,
                "label": label,
                "bucket": bucket,
                "source": filename,
            })
    return examples


def _detect_digital_content(img):
    pixels = img.reshape(-1, 3)
    unique_colors = len(np.unique(pixels, axis=0))
    total_pixels = img.shape[0] * img.shape[1]
    diversity_ratio = unique_colors / total_pixels

    if diversity_ratio < 0.05:
        return 0.3
    if diversity_ratio < 0.15:
        return 0.1
    return 0.0


def _analyze_color(frames):
    import cv2

    scores = []
    for frame in frames:
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        saturation = hsv[:, :, 1].mean()
        if saturation > 150:
            scores.append(0.7)
        elif saturation > 120:
            scores.append(0.4)
        else:
            scores.append(0.1)
    return scores


def _analyze_metadata(metadata):
    if not isinstance(metadata, dict):
        return 0.0, 0.0

    disclosure = str(metadata.get("youtubeAiDisclosure", "") or "").lower()
    import re
    if re.search(r'\bai\b|synthetic|altered', disclosure):
        return 1.0, 1.0

    disclosure_phrases = [
        "altered or synthetic content",
        "synthetic content",
        "ai-generated",
        "ai generated",
        "created with ai",
        "made with ai",
        "generated with ai"
    ]
    if any(phrase in disclosure for phrase in disclosure_phrases):
        return 1.0, 1.0

    fields = [
        metadata.get("title", ""),
        metadata.get("description", ""),
        metadata.get("channel", ""),
        " ".join(metadata.get("tags", []) or []),
        " ".join(metadata.get("categories", []) or []),
        metadata.get("youtubeAiDisclosure", "")
    ]
    text = " ".join(str(f) for f in fields if f).lower()
    if not text.strip():
        return 0.0, 0.0

    strong_terms = [
        "ai generated", "generated by ai", "made with ai", "text to video",
        "image to video", "ai video", "ai short", "synthetic video",
        "altered or synthetic content", "created with ai", "generated with ai"
    ]
    tool_terms = [
        "runway", "sora", "pika", "kling", "hailuo", "luma", "dream machine",
        "veo", "midjourney", "stable diffusion", "sdxl", "gen-3", "gen 3",
        "prompt", "comfyui"
    ]
    weak_terms = ["generated", "artificial", "deepfake", "cgi", "vfx"]

    hits = []
    score = 0.0
    for term in strong_terms:
        if term in text:
            hits.append(term)
            score += 0.35
    for term in tool_terms:
        if term in text:
            hits.append(term)
            score += 0.18
    for term in weak_terms:
        if term in text:
            hits.append(term)
            score += 0.08

    hit_count = min(len(set(hits)), 6)
    return min(score, 0.85), hit_count / 6


def _fetch_metadata(url):
    try:
        cmd = ["yt-dlp", "--dump-json", "--skip-download", url]
        result = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
        raw = json.loads(result.stdout)
        return {
            "title": raw.get("title", ""),
            "description": raw.get("description", ""),
            "channel": raw.get("channel", "") or raw.get("uploader", ""),
            "tags": raw.get("tags", []) or [],
            "categories": raw.get("categories", []) or []
        }
    except Exception:
        return {}


def load_feedback(base_dir):
    path = os.path.join(base_dir, "training_data", "feedback.jsonl")
    if not os.path.exists(path):
        return []

    examples = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            correction = (row.get("correction") or "").lower()
            url = row.get("url")
            if correction not in {"real", "suspicious", "ai"} or not url:
                continue
            label = {"real": 0, "suspicious": 1, "ai": 2}[correction]
            content_type = row.get("content_type") or "feedback_uncategorized"
            examples.append({
                "url": url,
                "label": label,
                "bucket": f"feedback_{content_type}",
                "source": "feedback.jsonl",
                "feedback": row,
            })
    return examples


def download_frames(url, frame_count=12):
    import cv2

    fd, temp_path = tempfile.mkstemp(prefix="monet_eval_", suffix=".mp4")
    os.close(fd)

    try:
        cmd = ["yt-dlp", "-f", "best[ext=mp4]", "-o", temp_path, "--force-overwrites", url]
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)

        cap = cv2.VideoCapture(temp_path)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        fps = cap.get(cv2.CAP_PROP_FPS) or 30

        frames = []
        if total_frames > 0:
            indices = [min(total_frames - 1, int(round(i * 0.5 * fps))) for i in range(min(frame_count, total_frames))]
            for idx in indices:
                cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
                ok, frame = cap.read()
                if ok:
                    frames.append(frame)
        cap.release()
        return frames
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)


class FeatureExtractor:
    def __init__(self):
        from analyzers.texture import TextureAnalyzer
        from analyzers.biometrics import BiometricAnalyzer
        from analyzers.semantics import SemanticAnalyzer
        from analyzers.random_forest import RandomForestClassifier
        from analyzers.vit_detector import ViTDetector

        print("Initializing analyzers...")
        self.texture = TextureAnalyzer()
        self.biometrics = BiometricAnalyzer()
        self.semantics = SemanticAnalyzer()
        self.vit = ViTDetector()
        self.rf = RandomForestClassifier()
        self.feature_names = RandomForestClassifier.FEATURE_NAMES

    async def extract(self, url):
        metadata = _fetch_metadata(url)
        frames = download_frames(url)
        if not frames:
            raise RuntimeError("No frames extracted")

        texture_scores = [self.texture.analyze(frame)[0] for frame in frames]
        bio_scores = []
        for frame in frames:
            score, _ = await self.biometrics.analyze(frame)
            bio_scores.append(score)

        color_scores = _analyze_color(frames)
        semantic_score, _ = await self.semantics.analyze(frames)
        vit_mean, vit_max, vit_std, _ = self.vit.analyze_frame_stats(frames)
        metadata_score, metadata_hits = _analyze_metadata(metadata)
        digital_penalty = _detect_digital_content(frames[0])

        features = self.rf.extract_features(
            np.mean(texture_scores), np.max(texture_scores), np.std(texture_scores),
            np.mean(bio_scores), np.max(bio_scores), np.std(bio_scores),
            np.mean(color_scores), np.max(color_scores), np.std(color_scores),
            digital_penalty,
            semantic_score,
            vit_max,
            metadata_score=metadata_score,
            metadata_hits=metadata_hits,
            vit_mean=vit_mean,
            vit_max=vit_max,
            vit_std=vit_std,
        )[0]

        return {
            "features": features.tolist(),
            "metadata": metadata,
            "signals": dict(zip(self.feature_names, features.tolist())),
        }


def load_cache(path):
    if not path or not os.path.exists(path):
        return {}
    cache = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if row.get("url"):
                cache[row["url"]] = row
    return cache


def append_cache(path, row):
    if not path:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def class_metrics(rows):
    by_label = {}
    for label in LABELS:
        tp = sum(1 for r in rows if r["actual"] == label and r["predicted"] == label)
        fp = sum(1 for r in rows if r["actual"] != label and r["predicted"] == label)
        fn = sum(1 for r in rows if r["actual"] == label and r["predicted"] != label)
        precision = tp / (tp + fp) if tp + fp else 0.0
        recall = tp / (tp + fn) if tp + fn else 0.0
        f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
        by_label[label] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "support": sum(1 for r in rows if r["actual"] == label),
        }
    accuracy = sum(1 for r in rows if r["actual"] == r["predicted"]) / len(rows) if rows else 0.0
    return accuracy, by_label


def threshold_sweep(scored_rows):
    candidates = []
    for suspicious_threshold in [0.25, 0.28, 0.30, 0.32, 0.35, 0.40, 0.45]:
        for ai_threshold in [0.50, 0.55, 0.58, 0.60, 0.65, 0.70]:
            if suspicious_threshold >= ai_threshold:
                continue
            rows = []
            for row in scored_rows:
                updated = dict(row)
                updated["predicted"] = score_to_class(row["score"], ai_threshold, suspicious_threshold)
                rows.append(updated)
            accuracy, metrics = class_metrics(rows)
            macro_f1 = sum(m["f1"] for m in metrics.values()) / len(metrics)
            ai_recall = metrics[2]["recall"]
            real_precision = metrics[0]["precision"]
            candidates.append({
                "suspicious_threshold": suspicious_threshold,
                "ai_threshold": ai_threshold,
                "accuracy": accuracy,
                "macro_f1": macro_f1,
                "ai_recall": ai_recall,
                "real_precision": real_precision,
            })
    return sorted(candidates, key=lambda r: (r["macro_f1"], r["ai_recall"], r["accuracy"]), reverse=True)


def ai_recall_thresholds(sweep, min_real_precision=0.70):
    filtered = [row for row in sweep if row["real_precision"] >= min_real_precision]
    if not filtered:
        filtered = sweep
    return sorted(
        filtered,
        key=lambda r: (r["ai_recall"], r["macro_f1"], r["accuracy"]),
        reverse=True,
    )


def write_report(path, rows, sweep, feature_importance):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    accuracy, metrics = class_metrics(rows)
    errors = [r for r in rows if r["actual"] != r["predicted"]]
    false_positives = [r for r in errors if r["actual"] == 0 and r["predicted"] in {1, 2}]
    false_negatives = [r for r in errors if r["actual"] == 2 and r["predicted"] != 2]
    bucket_counts = Counter(r["bucket"] for r in errors)

    lines = [
        "# Monet Classification Evaluation",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        f"Examples evaluated: {len(rows)}",
        f"Accuracy: {accuracy:.1%}",
        f"Errors: {len(errors)}",
        "",
        "## Class Metrics",
        "",
        "| Class | Precision | Recall | F1 | Support |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]

    for label, name in LABELS.items():
        metric = metrics[label]
        lines.append(
            f"| {name} | {metric['precision']:.1%} | {metric['recall']:.1%} | "
            f"{metric['f1']:.1%} | {metric['support']} |"
        )

    lines.extend([
        "",
        "## Best Thresholds",
        "",
        "| Suspicious | AI | Accuracy | Macro F1 | AI Recall | Real Precision |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
    ])
    for row in sweep[:8]:
        lines.append(
            f"| {row['suspicious_threshold']:.2f} | {row['ai_threshold']:.2f} | "
            f"{row['accuracy']:.1%} | {row['macro_f1']:.1%} | "
            f"{row['ai_recall']:.1%} | {row['real_precision']:.1%} |"
        )

    lines.extend([
        "",
        "## Best Thresholds For Catching AI",
        "",
        "These favor AI recall while keeping real-video precision at roughly 70% or better when possible.",
        "",
        "| Suspicious | AI | Accuracy | Macro F1 | AI Recall | Real Precision |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
    ])
    for row in ai_recall_thresholds(sweep)[:8]:
        lines.append(
            f"| {row['suspicious_threshold']:.2f} | {row['ai_threshold']:.2f} | "
            f"{row['accuracy']:.1%} | {row['macro_f1']:.1%} | "
            f"{row['ai_recall']:.1%} | {row['real_precision']:.1%} |"
        )

    lines.extend(["", "## Error Buckets", ""])
    if bucket_counts:
        for bucket, count in bucket_counts.most_common():
            lines.append(f"- {bucket}: {count}")
    else:
        lines.append("- No errors found in this run.")

    lines.extend(["", "## Feature Importance", ""])
    if feature_importance:
        for name, importance in sorted(feature_importance.items(), key=lambda item: item[1], reverse=True):
            lines.append(f"- {name}: {importance:.3f}")
    else:
        lines.append("- Feature importance unavailable until the model is trained with matching features.")

    lines.extend(["", "## False Positives", ""])
    if false_positives:
        for row in false_positives[:25]:
            lines.append(
                f"- {row['url']} | score {row['score']:.3f} | predicted {LABELS[row['predicted']]}"
            )
    else:
        lines.append("- None.")

    lines.extend(["", "## False Negatives", ""])
    if false_negatives:
        for row in false_negatives[:25]:
            lines.append(
                f"- {row['url']} | score {row['score']:.3f} | predicted {LABELS[row['predicted']]}"
            )
    else:
        lines.append("- None.")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


async def main():
    parser = argparse.ArgumentParser(description="Evaluate Monet on labeled Shorts URLs.")
    parser.add_argument("--limit-per-class", type=int, default=None, help="Quick-run limit for each URL list.")
    parser.add_argument("--include-feedback", action="store_true", help="Include saved Real/AI feedback corrections.")
    parser.add_argument("--cache", default=None, help="Feature cache JSONL path.")
    parser.add_argument("--report", default=None, help="Markdown report output path.")
    args = parser.parse_args()

    from analyzers.random_forest import RandomForestClassifier

    base_dir = os.path.dirname(os.path.abspath(__file__))
    cache_path = args.cache or os.path.join(base_dir, "training_data", "feature_cache.jsonl")
    report_path = args.report or os.path.join(base_dir, "training_data", "evaluation_report.md")
    model_path = os.path.join(base_dir, "analyzers", "random_forest.pkl")

    examples = load_sources(base_dir, args.limit_per_class)
    if args.include_feedback:
        examples.extend(load_feedback(base_dir))

    if not examples:
        print("No examples found.")
        return

    cache = load_cache(cache_path)
    extractor = FeatureExtractor()
    model = RandomForestClassifier(model_path=model_path)

    rows = []
    for idx, example in enumerate(examples, start=1):
        url = example["url"]
        print(f"[{idx}/{len(examples)}] {url}")
        try:
            cached = cache.get(url)
            if cached and len(cached.get("features", [])) == len(FEATURE_NAMES):
                feature_row = cached
            else:
                feature_row = await extractor.extract(url)
                feature_row.update({"url": url})
                append_cache(cache_path, feature_row)

            features = np.array([feature_row["features"]])
            score, _, _, confidence = model.predict(features)
            predicted = score_to_class(score)

            rows.append({
                "url": url,
                "actual": example["label"],
                "predicted": predicted,
                "score": float(score),
                "confidence": float(confidence),
                "bucket": example["bucket"],
                "source": example["source"],
                "signals": feature_row.get("signals", {}),
            })
        except Exception as e:
            print(f"  skipped: {e}")

    if not rows:
        print("No examples could be evaluated.")
        return

    sweep = threshold_sweep(rows)
    write_report(report_path, rows, sweep, model.get_feature_importance())

    accuracy, metrics = class_metrics(rows)
    print(f"\nEvaluated {len(rows)} examples")
    print(f"Accuracy: {accuracy:.1%}")
    print(f"AI recall: {metrics[2]['recall']:.1%}")
    print(f"Report saved to: {report_path}")


if __name__ == "__main__":
    asyncio.run(main())
