
import os
import cv2
import sys
import asyncio
import json
import numpy as np
import subprocess
import tempfile
import warnings
from pathlib import Path

# Silence protobuf deprecation warnings
warnings.filterwarnings("ignore", message=".*SymbolDatabase.GetPrototype.*")

# Add server directory to path so we can import analyzers
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from analyzers.texture import TextureAnalyzer
from analyzers.biometrics import BiometricAnalyzer
from analyzers.semantics import SemanticAnalyzer
from analyzers.random_forest import RandomForestClassifier
from analyzers.vit_detector import ViTDetector

# --- Helper functions duplicated from server.py to avoid import side-effects ---

def _detect_digital_content(img):
    """Detect games/screen recordings to reduce false positives"""
    pixels = img.reshape(-1, 3)
    unique_colors = len(np.unique(pixels, axis=0))
    total_pixels = img.shape[0] * img.shape[1]
    diversity_ratio = unique_colors / total_pixels
    
    if diversity_ratio < 0.05:
        return 0.3 #Digital content detected
    elif diversity_ratio < 0.15:
        return 0.1 #Limited color palette
    return 0.0 #Natural scene

def _analyze_color(frames):
    """Check for AI oversaturation"""
    scores = []
    for frame in frames:
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        saturation = hsv[:, :, 1].mean()
        if saturation > 150:
            scores.append(0.7)
        elif saturation > 120:
            scores.append(0.4)
        else:
            scores.append(0.1)
    return scores

def _analyze_metadata(metadata):
    if not isinstance(metadata, dict):
        return 0.0, 0.0

    disclosure = str(metadata.get("youtubeAiDisclosure", "") or "").lower()
    import re
    if re.search(r'\bai\b|synthetic|altered', disclosure):
        return 1.0, 1.0

    disclosure_phrases = [
        "altered or synthetic content",
        "synthetic content",
        "ai-generated",
        "ai generated",
        "created with ai",
        "made with ai",
        "generated with ai"
    ]
    if any(phrase in disclosure for phrase in disclosure_phrases):
        return 1.0, 1.0

    fields = [
        metadata.get("title", ""),
        metadata.get("description", ""),
        metadata.get("channel", ""),
        " ".join(metadata.get("tags", []) or []),
        " ".join(metadata.get("categories", []) or []),
        metadata.get("youtubeAiDisclosure", "")
    ]
    text = " ".join(str(f) for f in fields if f).lower()
    if not text.strip():
        return 0.0, 0.0

    strong_terms = [
        "ai generated", "generated by ai", "made with ai", "text to video",
        "image to video", "ai video", "ai short", "synthetic video",
        "altered or synthetic content", "created with ai", "generated with ai"
    ]
    tool_terms = [
        "runway", "sora", "pika", "kling", "hailuo", "luma", "dream machine",
        "veo", "midjourney", "stable diffusion", "sdxl", "gen-3", "gen 3",
        "prompt", "comfyui"
    ]
    weak_terms = ["generated", "artificial", "deepfake", "cgi", "vfx"]

    hits = []
    score = 0.0
    for term in strong_terms:
        if term in text:
            hits.append(term)
            score += 0.35
    for term in tool_terms:
        if term in text:
            hits.append(term)
            score += 0.18
    for term in weak_terms:
        if term in text:
            hits.append(term)
            score += 0.08

    hit_count = min(len(set(hits)), 6)
    return min(score, 0.85), hit_count / 6

def _fetch_metadata(url):
    try:
        cmd = ["yt-dlp", "--dump-json", "--skip-download", url]
        result = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
        import json
        raw = json.loads(result.stdout)
        return {
            "title": raw.get("title", ""),
            "description": raw.get("description", ""),
            "channel": raw.get("channel", "") or raw.get("uploader", ""),
            "tags": raw.get("tags", []) or [],
            "categories": raw.get("categories", []) or []
        }
    except Exception:
        return {}

def _feedback_label(correction):
    mapping = {
        "real": 0,
        "suspicious": 1,
        "ai": 2
    }
    return mapping.get((correction or "").lower())

def _load_feedback_examples(base_dir):
    feedback_path = os.path.join(base_dir, "training_data", "feedback.jsonl")
    if not os.path.exists(feedback_path):
        return []

    examples = []
    seen = set()
    with open(feedback_path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue

            label = _feedback_label(row.get("correction"))
            url = row.get("url")
            if label is None or not url:
                continue

            key = (url, label, row.get("content_type"))
            if key in seen:
                continue
            seen.add(key)

            metadata = row.get("metadata") or {}
            content_type = row.get("content_type") or "feedback_uncategorized"
            content_label = row.get("content_label") or content_type
            examples.append({
                "url": url,
                "label": label,
                "metadata": metadata,
                "source": f"feedback:{content_label}",
                "content_type": content_type
            })

    return examples

async def _extract_training_features(url, label, analyzers, rf, metadata=None):
    texture, biometrics, semantics, vit = analyzers
    temp_path = None

    if metadata is None:
        metadata = _fetch_metadata(url)

    try:
        fd, temp_path = tempfile.mkstemp(prefix="monet_train_", suffix=".mp4")
        os.close(fd)

        cmd = ["yt-dlp", "-f", "best[ext=mp4]", "-o", temp_path, "--force-overwrites", url]
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)

        cap = cv2.VideoCapture(temp_path)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        frames = []
        if total_frames > 0:
            num_sample = min(12, total_frames)
            fps = cap.get(cv2.CAP_PROP_FPS) or 30
            indices = [min(total_frames - 1, int(round(i * 0.5 * fps))) for i in range(num_sample)]
            for idx in indices:
                cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
                ret, frame = cap.read()
                if ret:
                    frames.append(frame)

        cap.release()

        if len(frames) < 1:
            raise RuntimeError("No frames extracted")

        t_scores = [texture.analyze(f)[0] for f in frames]
        texture_mean = np.mean(t_scores)
        texture_max = np.max(t_scores)
        texture_std = np.std(t_scores)

        b_scores = []
        for f in frames:
            s, _ = await biometrics.analyze(f)
            b_scores.append(s)

        if b_scores:
            bio_mean = np.mean(b_scores)
            bio_max = np.max(b_scores)
            bio_std = np.std(b_scores)
        else:
            bio_mean = 0.0
            bio_max = 0.0
            bio_std = 0.0

        color_scores = _analyze_color(frames)
        color_mean = np.mean(color_scores)
        color_max = np.max(color_scores)
        color_std = np.std(color_scores)

        digital_penalty = _detect_digital_content(frames[0])
        semantic_score, _ = await semantics.analyze(frames)
        vit_mean, vit_max, vit_std, _ = vit.analyze_frame_stats(frames)
        metadata_score, metadata_hits = _analyze_metadata(metadata)

        features = rf.extract_features(
            texture_mean, texture_max, texture_std,
            bio_mean, bio_max, bio_std,
            color_mean, color_max, color_std,
            digital_penalty,
            semantic_score,
            vit_max,
            metadata_score=metadata_score,
            metadata_hits=metadata_hits,
            vit_mean=vit_mean,
            vit_max=vit_max,
            vit_std=vit_std
        )

        summary = f"Bio={bio_mean:.2f}, ViT mean={vit_mean:.2f}, ViT max={vit_max:.2f}, ViT std={vit_std:.2f}, Label={label}"
        return features[0], summary
    finally:
        if temp_path and os.path.exists(temp_path):
            os.remove(temp_path)



async def main():
    print("="*60)
    print("MONET: CUSTOM TRAINING (YouTube Pipeline)")
    print("="*60)
    
    print("Initializing Analyzers...")
    texture = TextureAnalyzer()
    biometrics = BiometricAnalyzer()
    semantics = SemanticAnalyzer() 
    vit = ViTDetector()
    
    rf = RandomForestClassifier()
    
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_sources = [
        (os.path.join(base_dir, 'training_data', 'urls_real.txt'), 0), 
        (os.path.join(base_dir, 'training_data', 'urls_suspicious.txt'), 1),  
        (os.path.join(base_dir, 'training_data', 'urls_fake.txt'), 2)       
    ]
    
    X = []
    y = []
    
    total_videos = 0
    
    analyzers = (texture, biometrics, semantics, vit)

    for url_file, label in data_sources:
        if not os.path.exists(url_file):
            print(f"Skipping {url_file} (Not found)")
            continue
            
        with open(url_file, 'r') as f:
            urls = [line.strip() for line in f if line.strip() and not line.startswith('#')]
            
        print(f"Found {len(urls)} videos in {url_file}")
        total_videos += len(urls)
        
        for i, url in enumerate(urls):
            print(f"[{i+1}/{len(urls)}] Processing: {url}")
            try:
                features, summary = await _extract_training_features(url, label, analyzers, rf)
                X.append(features)
                y.append(label)
                print(f"  > Done. {summary}")
            except Exception as e:
                print(f"  > Failed: {e}")
                import traceback
                traceback.print_exc()
                continue

    feedback_examples = _load_feedback_examples(base_dir)
    if feedback_examples:
        print(f"Found {len(feedback_examples)} categorized feedback examples")
        for i, example in enumerate(feedback_examples):
            label = example["label"]
            print(f"[feedback {i+1}/{len(feedback_examples)}] {example['content_type']}: {example['url']}")
            try:
                features, summary = await _extract_training_features(
                    example["url"],
                    label,
                    analyzers,
                    rf,
                    metadata=example.get("metadata")
                )
                X.append(features)
                y.append(label)
                print(f"  > Done. {summary}")
            except Exception as e:
                print(f"  > Feedback example failed: {e}")
                import traceback
                traceback.print_exc()
                continue

    if not X:
        print("\nNo training data collected. Check URL files and internet connection.")
        return

    print(f"\nTraining Model on {len(X)} samples...")
    try:
        try:
            from sklearn.metrics import classification_report, confusion_matrix
            from sklearn.model_selection import train_test_split

            if len(set(y)) > 1 and min(np.bincount(np.array(y))) >= 2:
                X_train, X_test, y_train, y_test = train_test_split(
                    X, y, test_size=0.2, random_state=42, stratify=y
                )
                eval_rf = RandomForestClassifier()
                eval_rf.train(X_train, y_train)
                preds = []
                for row in X_test:
                    features = np.array([row])
                    score, _, _, _ = eval_rf.predict(features)
                    if score >= 0.58:
                        preds.append(2)
                    elif score >= 0.32:
                        preds.append(1)
                    else:
                        preds.append(0)

                print("\nHeld-out Evaluation:")
                print(classification_report(
                    y_test, preds,
                    target_names=["Authentic", "Suspicious", "AI"],
                    zero_division=0
                ))
                print("Confusion Matrix:")
                print(confusion_matrix(y_test, preds))
        except Exception as e:
            print(f"Evaluation skipped: {e}")

        rf.train(X, y)
        
        save_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "analyzers", "random_forest.pkl")
        rf.save(save_path)
        print(f"SUCCESS! Model saved to: {save_path}")
        print("Please restart the server to load the new model.")
    except Exception as e:
        print(f"Training failed: {e}")

if __name__ == "__main__":
    asyncio.run(main())
